name = 'book-series-showcase-e6b5967c'
compatibility_date = "2026-02-07"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "holy.nunchucks.com"
custom_domain = true