name = "book-series-showcase"
compatibility_date = "2026-02-07"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[routes]]
pattern = "holy.nunchucks.com"
custom_domain = true